spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/projetox
    username: postgres
    password: admin
server:
  port: 8081
  servlet:
    context-path: /projetox/v1